name: BugSearch Workflow

# on:
#  push:
#    branches: [ "master" ]
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
# on: workflow_dispatch


env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.0' # Specify your desired Qt version
        host: 'linux' # Or 'windows', 'mac'
        target: 'desktop'
        arch: 'gcc_64' # Or appropriate architecture for your host/target
        install-deps: 'true' # Install necessary build dependencies
        cache: 'true' # Enable caching for faster run

    - name: Install Boost
      run: |
         sudo apt-get update
         sudo apt-get install libboost-all-dev # Or specific Boost components like libboost-program-options-dev
         
    - name: Install libclang
      run: |
         sudo apt-get update
         sudo apt-get install -y libclang1

    - name: Install Doxygen
      run: |
         sudo apt update
         sudo apt install doxygen

#    - name: Setup LCOV
#      uses: hrishikesh-kadam/setup-lcov@v1
#    - name: Report code coverage
#      uses: zgosalvez/github-actions-report-lcov@v4
#      with:
#        coverage-files: coverage/lcov.*.info
#        minimum-coverage: 90
#        artifact-name: code-coverage-report
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        working-directory: ${{github.workspace}}/build/tst/CMakeFiles/BugSearch_tst.dir/
#        update-comment: true

    - name: Execute Build script
      run: ${{github.workspace}}/manual_test/linux_test.sh
